### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by toonsevrin** [maxence-charriere/go-app#392]
Is there or will there be support for server side rendering? 

I think this would be extremely useful for smaller websites.

**Comment by toonsevrin** [comment]
Nvm, I just read this is a PWA. Anyways, it would be cool to have client/server interaction as a first class citizen! A library that would allow the client to call functions on the server and visa-versa :)

**Comment by maxence-charriere** [comment]
This would force the way people are doing their interaction client/server. 

This subject can be very opinionated. For example, I'm totally satisfied with the Go standard HTTP model but some other people love to have another layer (which can be different depending on the tastes or needs).

If **go-app** starts to force people to do that in a defined way, some might be happy but it will also close the door to the one that does not agree with the way it is done.

This is just to give an insight into why this did not have already be done.

After nothing is defined forever. If someone comes with a very elegant idea that would fit most of the scenario, this might change my stance.
Just I don't have this solution at the moment.

**Comment by toonsevrin** [comment]
Of course, it speaks for itself that this would be completely opt-in as it only makes sense if rapid application development is important (which is the case for 90% of our projects).

**Comment by toonsevrin** [comment]
Anyways, I think we can create a testing version of this in a couple of minutes (I haven't looked at the go-app source so perhaps this is more difficult then I would think).

You would simply make the page serving interface pluggable:
A server side interface like this one would do the trick (though I recommend thinking this a bit more through as you can probably recycle the client-side router for better type safety):
```go
type Server interface { // I'm not good at naming stuff
    UI(req *app.Request) *app.UI
}
```
Note that for the proof of concept, app.Request could just contain the route string and the http.Request.

**Comment by sesopenko** [comment]
I have a somewhat similar need, where I'm trying to use the library to build a static site and server api all in the same language. I've pulled in mux-Gorilla to handle routing for my API but this library's Handler.ServeHTTP method encapsulates the routes which I need to ensure go to it. I thought about creating mux-Gorilla mux routes for routes such as `/wasm_exec.js` and `/app.js` but it would be fragile.

Can we invert the dependency somehow, by introducing a router to this library, as an alternative for people who can't use the full blown Handler implementation?  Something which can work with http.Handle() so that the library plays nice with other routes from outside the framework?  It'd be a step towards solving this problem, too.

**Comment by leedstyh** [comment]
Not having much thought on how to achieve this, but for me building a "gatsby like" in golang would be very interesting.

**Comment by maxence-charriere** [comment]
So I ran into this problem to solve SEO issues.
Server-side rendering (would call that more like pre-rendering) is implemented on V8. I had to make some API changes to make it work but it is coming. I already use it on https://murlok.io. Just polishing the release and updating the documentation and it will be available soon.

**Comment by maxence-charriere** [comment]
Should be solved by v8
