### ISSUE TITLE
Rendering composition/Slots

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#434]
As applications grow and functionality gets split into components a question arises. Can we do rendering composition similar to slots in js frontend frameworks ? For example let's say we have 3 different sections as part of a SPA. If we split them in 3 different components can we render them on demand from a root component thus doing async rendering only for the part of the html we want re-rendered ? 

As an example from the demo: https://github.com/maxence-charriere/go-app-demo/tree/V7/luck/app

If we had a render method in game.go can we call it from home.go without re-rendering home.go itself ?

**Comment by maxence-charriere** [comment]
If you keep references on those 3 components, you can call their Update method from the root.

I would not recommend it though since the logic to update a UI element works as a merge new in old. If your 3 component have different types it should not be a problem. Otherwise you may run into unwanted updates in the event you update the whole root.
