### ISSUE TITLE
Is there any way to get js dom value?

### ISSUE THREAD

**Issue by yms2772** [maxence-charriere/go-app#450]
I want to get current time of Youtube (iframe).
In javascript, I can call like below.
```javascript
ytplayer = document.getElementById("movie_player");
ytplayer.getCurrentTime();
```

Is there a way?

**Comment by maxence-charriere** [comment]
What you want to write would be as the following in go

```go
ytplayer := app.Window().GetElementByID("movie_player")
t := ytplayer.Call("getCurrentTime").Int()
```

Just it might not work because you need to deal with more than this to get this from the youtube API.
=> https://developers.google.com/youtube/iframe_api_reference

Check this repo if you are interested => 
- https://github.com/maxence-charriere/lofimusic
- https://github.com/maxence-charriere/lofimusic/blob/master/bin/lofimusic/player.go

**Comment by yms2772** [comment]
> What you want to write would be as the following in go
> 
> ```go
> ytplayer := app.Window().GetElementByID("movie_player")
> t := ytplayer.Call("getCurrentTime").Int()
> ```
> 
> Just it might not work because you need to deal with more than this to get this from the youtube API.
> => https://developers.google.com/youtube/iframe_api_reference
> 
> Check this repo if you are interested =>
> 
> * https://github.com/maxence-charriere/lofimusic
> * https://github.com/maxence-charriere/lofimusic/blob/master/bin/lofimusic/player.go

`player.go` is very helpful for me. Thank you!
