### ISSUE TITLE
Where should I execute the fectch data commnad?

### ISSUE THREAD

**Issue by gepengscu** [maxence-charriere/go-app#467]
Where should I execute the fectch data commnad (fetch data from a REST service), OnNav or OnMount or other palace?

**Comment by maxence-charriere** [comment]
Depends. It works in both. 

OnMount is called just when the component is mounted.

On nav is called when a page is navigated on. The component can already be mounted. So in this scenario, the component is reused and its content change depending of the page url path.

You should do it in a goroutine in order to not block the ui and use dispatch to update component field when you get the result. See the concurrency topic in the doc.

**Comment by gepengscu** [comment]
Thank u!

**Comment by jwmach1** [comment]
As a side note, this might be considered an enhancement request for the lifecycle picture. 

https://go-app.dev/components#lifecycle

It could help adoption of the framework if questions like these didn't need to be explored.  For example, to answer the OPs question when I started -- I put some println statements in each method and navigated around my app.

I mention this lifecycle picture because the lifecycle is not linear, there is an outer/inner loop.

**Comment by maxence-charriere** [comment]
Could definitely improve the doc. Any suggestion about where/how it would have made you understand it better?

You are pointing that schema but i m not sure i see how to make it better.

Sent from my iPhone

On Dec 22, 2020, at 8:54 PM, James <notifications@github.com> wrote:

﻿

As a side note, this might be considered an enhancement request for the lifecycle picture.

https://go-app.dev/components#lifecycle

It could help adoption of the framework if questions like these didn't need to be explored. For example, to answer the OPs question when I started -- I put some println statements in each method and navigated around my app.

I mention this lifecycle picture because the lifecycle is not linear, there is an outer/inner loop.
