### ISSUE TITLE
Print the generated HTML directly in the test program

### ISSUE THREAD

**Issue by gepengscu** [maxence-charriere/go-app#468]
How can I print the render HTML directly in the test program? It's difficult to debug a wasm program.

**Comment by maxence-charriere** [comment]
You cant. It does not generate html but interact directly with the Dom. Usually the way I m doing to check html is using chrome inspect mode.

**Comment by maxence-charriere** [comment]
What do you call the test program ? Is it unit test? If not what how would you use it and what does it brings that the chrome inspect tool dont?

**Comment by gepengscu** [comment]
Yes. I want to test program in unit test mode.

**Comment by maxence-charriere** [comment]
I could provide a function to print the rendered html but have to work on it a bit.
I ll let this open and see what I can do.

**Comment by gepengscu** [comment]
Thank u!

**Comment by maxence-charriere** [comment]
Let this open until its done ;)

**Comment by andrewrynhard** [comment]
I am actually interested in this for other reasons. We can't use Wasm due to limitations with it so for now we are looking at using hotwire.dev. With Hotwire we can stick with go and only have to render HTML, avoiding JS. So far in our PoC it is working well, but I hate having to work with go templates. I would actually _love_ to be able to build the HTML in go and render it out. We could us `app` for this.

**Comment by maxence-charriere** [comment]
Its coming, I m working on v8 which brings server side prerendering for SEO purpose. Already made the function there :).

**Comment by maxence-charriere** [comment]
This was solved in v8 => https://go-app.dev/reference#HTMLString.
