### ISSUE TITLE
Panic when calling Update() on component

### ISSUE THREAD

**Issue by ZackaryWelch** [maxence-charriere/go-app#512]
After updating to v8, all instances where Update is called on a component panic due to a null pointer exception as follows:

    panic: runtime error: invalid memory address or nil pointer dereference [recovered] wasm_exec.js:50:14
    panic: runtime error: invalid memory address or nil pointer dereference wasm_exec.js:50:14
    [signal 0xb code=0x0 addr=0x0 pc=0x0] wasm_exec.js:50:14
    <empty string> wasm_exec.js:50:14
    goroutine 1 [running]: wasm_exec.js:50:14
    github.com/maxence-charriere/go-app/v8/pkg/app.RunWhenOnBrowser.func1() wasm_exec.js:50:14
    /home/zcoupon/go/pkg/mod/github.com/maxence-charriere/go-app/v8@v8.0.0/pkg/app/app.go:103 +0x4 wasm_exec.js:50:14
    panic(0x5e840, 0x5651b0) wasm_exec.js:50:14
    /usr/lib/golang/src/runtime/panic.go:965 +0x19 wasm_exec.js:50:14
    github.com/maxence-charriere/go-app/v8/pkg/app.(*Compo).Defer(0x896000, 0x8d1750) wasm_exec.js:50:14
    /home/zcoupon/go/pkg/mod/github.com/maxence-charriere/go-app/v8@v8.0.0/pkg/app/component.go:177 +0xb wasm_exec.js:50:14
    github.com/maxence-charriere/go-app/v8/pkg/app.(*Compo).Update(0x896000) wasm_exec.js:50:14
    /home/zcoupon/go/pkg/mod/github.com/maxence-charriere/go-app/v8@v8.0.0/pkg/app/component.go:189 +0x5 wasm_exec.js:50:14
    main.(*Session).HidePopup(...) wasm_exec.js:50:14
    /home/zcoupon/repos/tc-saas-backend/src-web/newportal/src-wasm/session-functions.go:74 wasm_exec.js:50:14
    main.(*Session).ChangePage(0x896000, 0xc4ffe, 0x1) wasm_exec.js:50:14
    /home/zcoupon/repos/tc-saas-backend/src-web/newportal/src-wasm/session-functions.go:64 +0x14 wasm_exec.js:50:14
    main.(*FormLogin).Login(0x83a120, 0x12a218, 0x839240, 0xe75fd8, 0x84fe00, 0x12e7e0, 0x8bf190, 0x0, 0x12ca30, 0x80a0d8, ...) wasm_exec.js:50:14
    /home/zcoupon/repos/tc-saas-backend/src-web/newportal/src-wasm/form-login.go:51 +0x1d wasm_exec.js:50:14
    github.com/maxence-charriere/go-app/v8/pkg/app.makeJsEventHandler.func1.1() wasm_exec.js:50:14
    /home/zcoupon/go/pkg/mod/github.com/maxence-charriere/go-app/v8@v8.0.0/pkg/app/node.go:159 +0xd wasm_exec.js:50:14
    github.com/maxence-charriere/go-app/v8/pkg/app.(*uiDispatcher).start(0x832360, 0x12a250, 0x810040) wasm_exec.js:50:14
    /home/zcoupon/go/pkg/mod/github.com/maxence-charriere/go-app/v8@v8.0.0/pkg/app/dispatcher.go:273 +0x5 wasm_exec.js:50:14
    github.com/maxence-charriere/go-app/v8/pkg/app.RunWhenOnBrowser() wasm_exec.js:50:14
    /home/zcoupon/go/pkg/mod/github.com/maxence-charriere/go-app/v8@v8.0.0/pkg/app/app.go:133 +0x61 wasm_exec.js:50:14
    main.main() wasm_exec.js:50:14
    /home/zcoupon/repos/tc-saas-backend/src-web/newportal/src-wasm/main.go:15 +0x11

**Comment by maxence-charriere** [comment]
I assume this is the root addr.
Is it possible to see the main and the routes ?

**Comment by maxence-charriere** [comment]
Did you removed the build instructions ?

**Comment by ZackaryWelch** [comment]
Reloading it, rebuilding, or moving where Update is called does not change anything, neither does using a private tab.

I shortened the stack trace but I just updated it for the full version.

**Comment by maxence-charriere** [comment]
Any chance to see the code of form-login.go and sessions-function.go ?

I can do a quick call with share screen if you are up to.

**Comment by maxence-charriere** [comment]
Hey @ZackaryWelch, I'm sorry that you get into trouble for that migration. I just updated the [migration guide](https://go-app.dev/v7-to-v8) with the `build directives` and `routing` sections. Those were unclear and might be something you missed.

Let me know how it goes. I have to leave right now but if you need, we can set a zoom meeting for me to help you solve those problems.

**Comment by ZackaryWelch** [comment]
Thanks, I think that was it! I'll post an update if it's fixed or I still have issues.

**Comment by beanpole135** [comment]
Just chiming in on this since Zack contacted me about the issue too, since he was trying to convert my v7 go-app template site to v8.

The v8 version of this template is proving to be a bit of a challenge... I narrowed down the crash that Zack reported above to the main "Render()" function of the session component having a nil "Main Page" assigned within the browser.
This appears to have exposed a "disconnect" in the code between the browser-side and server-side, because I littered console/log messages throughout the session struct, and in both the browser and the server, I am getting the message that it loaded the page - but the moment the Render() function runs, the selected page object is nil again - almost like go-app is resetting the object back to it's pre-initialized state.

You can view/build the templates from here:
V7 (works great): https://github.com/beanpole135/go-site-templates/tree/go-app/v7/go-app-template
V8 (Not working yet): https://github.com/beanpole135/go-site-templates/tree/main/go-app-template

As an aside, my template was setup to facilitate running a site with a separate server side (with secret keys, logins, interaction API, etc), and the browser side (WASM) just included all the visual elements and rendering objects (SEO is not important to me - it treats the WASM site like an App with just a single "page"). With v8 and the combined nature of the server/browser code, I am not sure this type of setup with work any more without making 2 different servers (one for serving the site, one for providing the API's/functionality). I don't suppose you could add an option to disable the server-side SEO integrations and allow it to be run/built separately again?

**Comment by beanpole135** [comment]
FYI: I Just did a bit more work to the v8 template-in-progress and removed all state fields from my "Session" (app.Compo) struct and moved them into a separate internal cache struct which *does* persist. This fixes the page loads, but re-exposes the go-app crash the moment the Update() function is called on that Session struct (before it ever even tries to run the Render() for the structure again). So I am inclined to think that something else is going on in go-app V8 internally which is causing the issues.

**Comment by maxence-charriere** [comment]
```
almost like go-app is resetting the object back to it's pre-initialized state.
```
This is correct. Now, go-app is storing only a type when using `Route()`. A new instance of the component is created when navigating to a new page. Component initialization should be done in `OnMount()` `OnPreRender()` or `OnNav()`.

Concerning having server/client logic separated is still a totally viable thing. I use this in https://murlok.io. Just now you don't need build directives anymore and you need to route also on the server-side.

**Comment by beanpole135** [comment]
Ok, that clarification let me fix the issue.
Because I was saving a pointer to the global "SESSION" component for use within all the individual components/files later, that was the one getting passed into `app.Route("/", SESSION)` function in main.go. Since app.Route was not actually using that object, but a separate copy/instantiation of the class, my global SESSION component was not actually hooked-in to the go-app rendering - causing the crash when I called SESSION.Update().

To get around this, I setup a first-run routine within the Session object itself to save itself into that global variable (so it always points to the "real" structure getting used by go-app), and now all the crashes are gone and things are working normally again.

Not sure if there is anything for you to do on your end - the key to fixing this was just that tidbit about the app.Route() function not actually using the structure it was given. Maybe just a quick note in the docs if you don't have one already and I think this issue can be closed.

FYI: I did get the server/browser "split" up and running again on my v8 template. I just created a blank "SEO" object which returns app.Div() to disable the SEO rendering on the server-side as needed.

**Comment by maxence-charriere** [comment]
Adding the precision in documentation in #514

**Comment by pojntfx** [comment]
I also ran into a similar problem (calling `*.Children` in a component in `app.Route`) when I tried to upgrade liwasc from v7 to v8; while I'll probably refactor and enable SSR for the data fetching in the future, I don't have the necessary resources right now, so I just moved the relevant code into a nested component which resolves the issue as it doesn't seem to get rendered on the server; see https://github.com/pojntfx/liwasc/commit/5c8d6f1113f7bf464c0f550305efc1ac56330477 for the full v7 to v8 upgrade commit and https://github.com/pojntfx/liwasc/commit/5c8d6f1113f7bf464c0f550305efc1ac56330477#diff-f240aa02b7d10612e62577a2b87428e88c00c54625144ef9ce55e017d2252639 diffed to https://github.com/pojntfx/liwasc/commit/5c8d6f1113f7bf464c0f550305efc1ac56330477#diff-7bc34e8cd187ba73967ac24eba3412e00d7db7036d49fa17ce3187e72c7a788d in particular for this solution.

**Comment by maxence-charriere** [comment]
Closing this since it is now documented. Reopen if you need.
