### ISSUE TITLE
Documentation lacks example where CLI and PWA logic would work within single module/package

### ISSUE THREAD

**Issue by HolimaX** [maxence-charriere/go-app#529]
Currently, the doc is focusing only on PWA use-case.

I would love to have example where also CLI (*.exe file is built and then is triggered via command line) is usable.

**Comment by maxence-charriere** [comment]
Mmm, I m not sure understand well here. Go-app is to build frontend UI that works in a web browser. Is vanilla Go is not already q good tool to build CLI ?

**Comment by maxence-charriere** [comment]
If you want a self contained app, you can use something like electron and make it point to  a local or diestant server.

**Comment by HolimaX** [comment]
> If you want a self contained app, you can use something like electron and make it point to a local or distant server.

Can you share links, please?

> Mmm, I m not sure to understand well here. Go-app is to build frontend UI that works in a web browser. Is vanilla Go is not already q good tool to build CLI ?

Imagine I have an .exe file, produced after 'go build' command. This executable file contains both PWA logic ( with http routes and rendered content ), and also CLI logic, that parses parameters and therefore has separate logic there via code like this:
```	
        scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
        ...
        }
```

**Comment by maxence-charriere** [comment]
> Imagine I have an .exe file, produced after 'go build' command. This executable file contains both PWA logic ( with http routes and rendered content ), and also CLI logic, that parses parameters and therefore has separate logic there via code like this:

This package is used as a standard HTTP Handler and server. It is launched by the command line like any other Go program. Look like your problem is more about getting a CLI argument and launch the server or something else depending on them.

If I'm correct I would suggest a look at the standard [flags](https://golang.org/pkg/flag/) package.

If you want something a little bit more advanced you can see what is done on go-app Docs's main.go => https://github.com/maxence-charriere/go-app/blob/master/docs/src/main.go

**Comment by maxence-charriere** [comment]
Seems like Go CLI-related issue. Closing this.
