### ISSUE TITLE
indexeddb support/library?

### ISSUE THREAD

**Issue by c-nv-s** [maxence-charriere/go-app#539]
Is it possible or are there plans to use go app to store data in indexeddb ?
if not, are there any existing libraries somewhere to help with this.

**Comment by gedw99** [comment]
This golang code compiled to wasm and integrates with indexdb.

https://github.com/JohnStarich/go-wasm/tree/master/internal/indexeddb

The project is a ide and golang compiler that runs 100% in a browser . Pretty nuts eh.

the std lib and OS that golang relies on in order to run on your computer is abstracted to use the browser primitive like indexdb. The file system is abstracted using indexdb , so when golang code needs a file system , it all works.

There are many other abstractions in the repo too.

It’s slow and big, but that is fixable by refactoring a few bits to use tinygo OR wait for tinygo to provide the “polyfils” for golang std packages like “net”, “fmt”, “reflect”, “json encoder”.

**Comment by JohnStarich** [comment]
Thanks for the shout out @gedw99!

I've extracted the IndexedDB adapter I wrote from `go-wasm` to [`go-indexeddb`](https://github.com/hack-pad/go-indexeddb), plus a file system library [`hackpadfs`](https://github.com/hack-pad/hackpadfs) that uses it.

They're both still in their first release, but you may find those useful 🙂

**Comment by maxence-charriere** [comment]
Not in the scope of go-app for now.
