### ISSUE TITLE
Setting custom HTML attributes

### ISSUE THREAD

**Issue by aervin** [maxence-charriere/go-app#554]
Hello and thanks for this fantastic project!

I'm wondering how to set custom attributes on elements? One use-case is integration with libraries that [make use of custom attributes](https://getuikit.com/docs/dropdown).

I've tested that things work fine when using `app.Raw(...)`. Is there a more specific API for this sort of thing?

**Comment by maxence-charriere** [comment]
Hey there, thank you for the kind words.

go-app follows HTML5 standard which says that custom attributes are prefixed with `data-`.
Look like the lib you are using has its own custom one.

Currently, it is not possible to set custom attributes other than data. I could modify it but have to experiment a bit with it.
It seems that this library uses the custom attributes for executing js code under the hood. 
That could cause a sync problem with go-app since its virtual dom might get out of sync with the real dom modified by that lib.

**Comment by aervin** [comment]
Yes that is a reasonable concern, and the library I referenced does not conform with HTML5 standards, you're right. However, I'd be happy to test 😃.

How do you imagine the API? Would you accept a PR for something like:
```
app.Div().Attr(<string>, <string? []byte?>).Body(/* ... */)
```

**Comment by maxence-charriere** [comment]
This is doable in current version.
