### ISSUE TITLE
js.Global() - imports syscall/js: build constraints exclude all Go files in /usr/lib/go-1.17/src/syscall/js

### ISSUE THREAD

**Issue by mar1n3r0** [maxence-charriere/go-app#701]
I have tried accessing the DOM in the hello demo app and this happened. I am curious as to what changed since previous versions where we had access to syscall/js. How do we fix it or do we have a new way to access it via helpers?

**Comment by oderwat** [comment]
I think this is only related to the IDE / Editor you are using. Configure it for the wasm target [VSCode Example](https://egghead.io/lessons/go-configure-go-build-constraints-in-vs-code-to-work-with-webassembly).

I think I needed to add wasm build constraints to some files in a mixed project to make it work.

```
//go:build wasm
```

**Comment by mar1n3r0** [comment]
Tried adding it:

`build constraints exclude all Go files in /home/mar1n3r0/Public/go-app-hello`

**Comment by oderwat** [comment]
Yes. Because they are not "only" compiling with the constraints set to wasm/js. You need to separate the code you want to use in the frontend from the one in the backend. Normal go code can not have syscall/js included.

But all of this should not be needed anyway. I only get those problems when I actually compile wasm code in the same project to be loaded as a plugin.

You should be able to do the dom manipulations you need through the go-app provided functions. Try `app.Window()` for a start.

If you really need syscall/js I think you should separate this in their own files or even packages and guard them with the `//go:build wasm` and `//go:build !wasm` so the compiler can pick what it needs for the two compilation runs you have with every go-app project.

**Comment by mar1n3r0** [comment]
Thanks, somehow totally missed the docs at: https://go-app.dev/js

Marking as resolved.
