### ISSUE TITLE
I need to skip component updates for event handler (a lot)

### ISSUE THREAD

**Issue by oderwat** [maxence-charriere/go-app#709]
If you currently add an even handler like "OnKeyUp()" the engine will always call update which in return will call render of the components. This can be wasteful of resources if you do not need to react to the event at all. This can happen a lot when you implement more complex components which need to react to changes while you are typing (validators for example).

I wished that the handlers had a return value, so we could simply return "true" or "false" if an update is needed or not. As this is not the case and I think it would break a lot of code to introduce it now, I could imagine that we get a `ctx.SkipUpdate()` function. I looked into the engine and think this should be quite easy by adding "SkipUpdate bool" to the Dispatcher and using it to skip the call to `e.scheduleComponentUpdate(d.Source)` in the engine. I am not sure how to add the `SkipUpdate()` to the context. 

What do you think @maxence-charriere?

**Comment by maxence-charriere** [comment]
This will be called once each “frame”. Like if you press a 10 keys within a 20ms interval, only 1 update will be called within this interval.

I’m not sure a breaking change is worth the performance gain here.

**Comment by oderwat** [comment]
This would be up to 50 calls to Render (and possibly more) per second, not to waste. I have debugging code on the calls, and it does look awful when you see how much happens because of the cascading rendering when you press, e.g., a cursor key.

Why do you say it is a breaking change? It would be one with having a return value for the handler. I think it could be a method of context (or event?), which sets a flag and then prevents calling the update. Similar to the `e.PreventDefault()` method.

**Comment by maxence-charriere** [comment]
A return value to the handler is a change of the api. It will break current code.

Maybe a prevent default like thing could work. Have to try.

Sent from my iPhone

On Apr 5, 2022, at 2:32 PM, Hans Raaf ***@***.***> wrote:

﻿

This would be up to 50 calls to Render (and possibly more) per second, not to waste. I have debugging code on the calls, and it does look awful when you see how much happens because of the cascading rendering when you press, e.g., a cursor key.

Why do you say it is a breaking change? It would be one with having a return value for the handler. I think it could be a method of context (or event?), which sets a flag and then prevents calling the update. Similar to the e.PreventDefault() method.

**Comment by oderwat** [comment]
I came up with some solution that seems to work. Maybe you can have a look at it or get inspired by it :)
