### ISSUE TITLE
Tutorial app doesn't start

### ISSUE THREAD

**Issue by andig** [maxence-charriere/go-app#718]
Followed the getting started, with one change to the `Makefile` to match the executable name:

	go build -o hello

```
make run
GOARCH=wasm GOOS=js go build -o web/app.wasm
go build -o hello
./hello
```

At this point, no UI or error is displayed. Not sure where to continue.

**Comment by mlctrez** [comment]
@andig   go-app does not launch the UI automatically, you need to point a browser at http://localhost:8000

**Comment by andig** [comment]
Oh dear... thank you! Is there any tutorial or example how to bundle a standalone app (Electron?).

**Comment by oderwat** [comment]
> Oh dear... thank you! Is there any tutorial or example how to bundle a standalone app (Electron?).

Not that I know of and go-app also is not meant to be used like that. It is for PWAs which can get installed by the user if he wishes to. So instead of letting a user download your Electron-based App for their platform, you simply tell them to follow the URL. You can [prompt the user to install your app](https://go-app.dev/install) when he is opening the browser at that location.

Though there may be ways to distribute PWAs packages for different platforms and even [put them into the App-Stores](https://www.simicart.com/blog/pwa-app-stores/).

**Comment by oderwat** [comment]
Using Electron is something very different. I guess one could make something similar to go-app with Electron as a target.

There are projects like https://github.com/asticode/go-astilectron which do that.

**Comment by oderwat** [comment]
I was thinking about it and one could use https://github.com/webview/webview (instead of Electron) to get rid of the browser dependency. It should be as easy as running the go-app server on a localhost port and loading this inside of webview running in another goroutine.
