### ISSUE TITLE
go-app on AWS Lambda

### ISSUE THREAD

**Issue by SonOfBytes** [maxence-charriere/go-app#744]
Has anyone managed to have go-app PWA serviced by AWS API Gateway to a Lambda hosting the go-app binary?

Any pointers to wrapping the lambda handler and responses to getting a working PWA?

**Comment by mlctrez** [comment]
I threw this together over the past few days, hopefully someone will find it useful.  
It uses a lambda function URL instead of  API gateway. 

https://github.com/mlctrez/goapplambda

The details of the AWS configuration are pretty high level, if there is a need I can add a bit more documentation on it.
