### ISSUE TITLE
Find way to have debug sessions directly from the IDE 

### ISSUE THREAD

**Issue by eakeur** [maxence-charriere/go-app#768]
I'm trying to build an application with go-app and created a simple form to check if the library would meet the requirements of the app. Fortunately, it does, but I cannot debug the application after it is compiled. The only thing that the IDE listens to is the main function and the first render of the main page. 

I would like to know if there is another way to debug it or if I am missing something like mappings that should be generated with the WASM (like JS mappings for chrome DevTools).

**Comment by oderwat** [comment]
You must distinguish between the server executable (backend) and the Wasm parts. 

You can debug the back end like with every other Go code (Delve/IDEs). 

Debugging in the front end means debugging the Wasm code inside the browser. This is possible, but the current implementation of the Go compiler and the debugger do not support the correct mappings. 

This makes it pretty hard/useless because you do not see your Go code there (yet). I think this problem is worked on. It was solved for TinyGo some days ago (I have not tried it yet). I think this will happen to work with the standard Go compiler-generated Wasm eventually, too. If it will be "nice" to do is another question.

Resources:

* https://blog.noops.land/debugging-webAssembly-from-go-sources-in-chrome-devtools
* https://developer.chrome.com/blog/wasm-debugging-2020/

As long as this is not possible, we are using the good old "print debugging," and we published some small packages to help with that by making it easy to see where calls to the log originated from: https://github.com/metatexx/go-app-pkgs/tree/master/dbg (best is to copy that, as we do guarantee nothing)

**Comment by gepengscu** [comment]
@maxence-charriere did a lot job. You can debug ui in unit test like this: 
```go
func TestSomeUI(t *testing.T) {
	t.Run("aName",
		func(t *testing.T) {
			ui := newYourUI()
			d := app.NewClientTester(ovl)
			defer d.Close()
			d.Consume()
			// call func of ui 
                        // ui.someFunc.......
                        // print...
		})
}
```

**Comment by eakeur** [comment]
Any news on that now? I stopped using the framework due to some personal reasons but I'm coming back to it

**Comment by maxence-charriere** [comment]
Since the app run in a browser, this would require that the client send the logs to the server. No plan to add this to go-app but it should not be hard to implement it yourself if you need it.
