### ISSUE TITLE
Running a web assembly application in a chrome extensioon

### ISSUE THREAD

**Issue by amlwwalker** [maxence-charriere/go-app#769]
This repository here[ demonstrates running web assembly](https://github.com/inflatablegrade/Extension-with-WASM/tree/manifest-v3) in a chrome extension. 

I found that as a result of the answer to this [stack overflow question](https://stackoverflow.com/questions/49611290/using-webassembly-in-chrome-extension). Note the manifest v3 version linked at the bottom.

That is based off of the [mozilla tutorial for web assembly here](https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API).

I am trying to do something similar using go-app as the basis for the web assembly application.

I have something like 

```go
func printMessage(this app.Value, inputs[]app.Value) interface{} {
	fmt.Println("printing message")
	app.Window().Call("alert", "hello world")
	message := "hello world"//inputs[0].String()
	document := app.Window().Get("document")
	p := document.Call("createElement", "p")
	p.Set("innerHTML", message)
	document.Get("body").Call("appendChild", p)
	return nil
}

func main() {
	app.Window().Set("go_printMessage", app.FuncOf(printMessage))
}
```

in my go-app main.go file.
I compile that with

```
GOARCH=wasm GOOS=js go build -o web/simple.wasm
go build
```

In the extension I am changing line 21 of content_script.js to 
```javascript
results.instance.exports.go_printMessage();
```
so that my function is the called function, and then import the same extension linked above into chrome as an unpacked extension.

This doesn't throw any errors but clicking the extension when on a webpage does not call my `printMessage()` function it seems.
My guess is that usually with a go-app application I have built I am running

```go
app.RunWhenOnBrowser()
if err := http.ListenAndServe(":8000", nil); err != nil {
 log.Fatal(err)
}
```

which I am not doing here (I did try it). 
Any suggestion on a "hello world" example of using go-app inside a chrome extension - i.e replacing simple.wasm with a go-app equivalent.
In the simple.wasm as I understand it, the code being called i.e the function `results.instance.exports.exported_func();` in turn calls the exposed `imported_func` which prints to the console.

I am trying to inject something into the DOM and print to the console in my `printMessage` function.
Any help greatly appreciated as to using go-app in a chrome extension like this. The ultimate goal is to build the web assembly go application and use UI capabilities to manipulate the DOM of a page the extension is run on.
Thanks!

**Comment by mlctrez** [comment]
Take a look at app.js in go-app on this line:
https://github.com/maxence-charriere/go-app/blob/70b80e95a439828752187d1968d2f9b711a63d20/pkg/app/gen/app.js#L215

I'm pretty sure you'll need to incorporate wasm_exec.js from https://github.com/golang/go/tree/master/misc/wasm in order to get this to work.  i.e.

```bash
cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .
```
main.js
```js
	chrome.scripting.executeScript({		
		target: {tabId: tabId},
		files: ["wasm_exec.js", "content_script.js"]
	});

```
content_script.js
``` js
var go;
if (go === null) {
    go = new Go();

    fetch(wasmPath).then(
        response => response.arrayBuffer()
    ).then(bytes =>
        WebAssembly.instantiate(bytes, go.importObject)
    ).then(results => {
        console.log("results");
        results.instance.exports.exported_func();
    });

}
```

There is also some lifecycle issues to work out like how many times the Go() object is instantiated in the context of an extension, etc.  Not sure if the starting point of https://github.com/inflatablegrade/Extension-with-WASM/tree/manifest-v3 would be correct for go-app.

**Comment by amlwwalker** [comment]
Fantastic I got this to work now. Nice one.
As a follow up question then I realise that one thing the docs don't cover is whether or not I can inject app components made using go-app into existing DOM elements.
So the idea being (for me) that my chrome extension will inject DOM elements that are made using go-app into the existing page. 
So for instance when my chrome extension is clicked, in javascript I am adding a sidebar down the right hand side (this works):
<img width="584" alt="image" src="https://user-images.githubusercontent.com/2920180/187627521-4ea0e420-7c6c-48fb-a5fb-5f1cc4e3c48e.png">

So then inside that sidebar I now want to add components built using go-app - i.e a mini wasm "area"

```go
	sidebar := app.Window().Get("overlay_sidebar")
	sidebarContent := layouts.FlexBox("100%",
		app.Range(icons).Slice(func(i int) app.UI {
			return app.Div().Class("column").Body(
				app.I().Class("icon icon-2x").Class(icons[i]),
			).Style("padding", "0.5rem")
		}),
	)
	sidebar.Call("appendChild", sidebarContent)
```

This throws an error which is tricky to debug 
```
panic: syscall/js: call of Value.Call on undefined
wasm_exec.js:22 
wasm_exec.js:22 goroutine 1 [running]:
wasm_exec.js:22 syscall/js.Value.Call({{}, 0x0, 0x0}, {0x3e553, 0xb}, {0x40fa20, 0x1, 0x1})
wasm_exec.js:22 	/usr/local/go/src/syscall/js/js.go:384 +0x35
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.value.Call({{{}, 0x0, 0x0}}, {0x3e553, 0xb}, {0x40fa20, 0x1, 0x1})
wasm_exec.js:22 	/Users/${user}/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/js_wasm.go:21 +0x7
wasm_exec.js:22 main.main()
```

however I suspect its because I am trying to inject "wasmy" components into dom components that aready exist. I actually thought that it maybe that my javascript injected sidebar doesn't exist yet causing the error, so I tried `sidebar := app.Window().Get("body")` but that throws the same error.

In the end I am interested in adding DOM elements to existing DOM components using go-app - is there a mechanism for this? I feel like it should be possible as I can do this with `syscall/js` directly although thats much nastier to use!

Thanks for this awesome library!

**Comment by oderwat** [comment]
I think using Go-App for this is "strange" because Go-App expects to have its page, and everything related to nodes works with this. I may be wrong, though, and since I use it to render HTML server-side, who am I to judge? I would think that going with GopherJS would probably be the way to go for an extension (JS or Wasm).

All the errors you show imply that you call them with an "undefined" value. Did you debug what they are? You can use `app.Window().Get("console").Call("log", msg)` to make debugging some stuff inside the browser easier. Maybe there are problems accessing the main page's DOM.

However, I fear there are no javascript nodes before something gets mounted by go-app. So, when you want to add content to an existing page, you may want to try using `app.HTMLString(yourUI)` and add the HTML code to the DOM.

P.S.: I have no idea what you are doing right now to get that sidebar based on Go-App.

**Comment by amlwwalker** [comment]
Thanks @oderwat 
To be clear - my goal is to "attach" buttons to certain DOM elements that exist on pages already, using a Chrome extension. By clicking them Go/Wasm function calls are fired.

I realise I can do alot of this through javascript in the extension and then get the JS to call wasm functions and that may well be the way to do it, I just really like using Go-App to build up UIs and had hoped I could inject these UIs into elements on the page from Go rather than javascript (minimising the amount of JS I have to write).
