### ISSUE TITLE
injecting scripts at the end of the HTML document

### ISSUE THREAD

**Issue by amlwwalker** [maxence-charriere/go-app#770]
If I want to inject a javascript script I can do 

```go
Scripts: []string{
	"/web/js/prism.js",
},
```
in the app handler.
Is there a place/way to inject them so they are loaded at the end of the HTML document rather than at the top? I realise I can probably do this per element, however it would be nice to do it globally across the app....

**Comment by oderwat** [comment]
I hope that I can help. I am not sure if I understood the problem correctly :)

It would help if you considered that the javascripts you set there are loading with "defer"(loaded parallel to the HTML and executed when the page has finished parsing). They all get cached and then loaded from there, so they are available even if there is no internet. That is what makes Go-App a PWA framework. So technically, they are loaded before your Wasm code executes.

If you want to load a script "at any time", you need to add them to the `CacheableResources` and then use `Render` in your components to emit a script tag that loads them (again from the cache through the web-worker fetch interface). So, in either case, they are already in memory (PWA again).

I think you do not care about when they load but want them to execute at another point. For this, I define functions in them on "windows" so the code can call them through `app.Window().Call("theFunc",theParams)` when they are needed.

I see you want to use `prism`. I did not use that one, but I guess it will not work because it runs before anything meaningful is on your "page". 

To make it work, I would probably use the "manual mode" of Prism and add the code `<script src="prism.js" data-manual></script>` to the `RawHeaders` section and add the `prism.js` to the `CacheableResources`. Then I would use the API to call `highlightAll()` after I updated the page (`Render()`). For example, when you update the component's model (`OnMount()` or at an Event Handler), you need the Context for that. So you would call `.Call("hightlightAll")` in a `defer()` section (to execute it after the update). I used something similar but have a debouncer and a timed go routine calling it through `dispatch()`. Maybe one even wants to render a call using a script tag in Render. I can think of many ways to do it, but typically we call it inside of event handlers that change the related component.

P.S.: I may try using prism.js in one of our apps with source code input to see how that works.

**Comment by amlwwalker** [comment]
thanks for the response @oderwat 

1. Prism is generally very easy to use in a static site. One css file, one JS file right before the closing `</body>` tag.

Although your explanation may work and when i get a chance I will try it, it seems overly complicated compared to the rest of how go-app 'replaces' standard web apps (which generally is fantastically easy). I was hoping that I could just somehow put scripts before the closing `</body>` tag and then just like usual let them execute when the browser calls them. It seems a bit "hacky" to have to manually call prism just because....


So you can see what I am experiencing when I do:

```go
Styles: []string{
			"/web/css/prism.css",
			...
```
and 
```go
func Page(title, description, src string, body ...app.UI) app.HTMLDiv {
	return app.Div().Class("container").Body(
		//...
		//... more elements that make up my page - therefore inserting prism.js last...
		app.Script().Src("/web/js/prism.js"),
	)
}
```

My web app loads and then on first load I will see something like:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/2920180/188154096-9f55d2ca-6b63-4256-bd91-a3cb526b3a0c.png">

if I then navigate to another page within the app and back again, I then see

<img width="448" alt="image" src="https://user-images.githubusercontent.com/2920180/188154439-cabef33a-cd5e-43e9-aa91-8a4a6fabf52b.png">


It seems prism loads partially after the first load but not immediately (its also only partially loading I believe - hence why there is no sytax highlighting, but I am getting the beige box...)

**Comment by oderwat** [comment]
I kind of wonder what you call "standard web apps"? VueJS, React, AngularJS, or just server-rendered HTML? Later one is something completely different. Maybe you could show me more of your code, so I can understand what you are doing there. To me, it sounds pretty strange to talk about "easy" together with any PWA code. That is all very complex compared to a static HTML side (even when using javascript). There are so many nuances about elements' lifetimes that it is easy to lose track of what happens.

**Comment by oderwat** [comment]
I added Prism pretty much as described above to an app of mine:

![prism-live-1](https://user-images.githubusercontent.com/719156/188200691-a7dd78b2-b9b7-44a7-b792-3f8a4dec3df8.gif)

It works pretty well. I need to set the HTML on input and call the highlighter. The code at the bottom is the prism output. The code on the top right is the one for TailwindCSS and is an iFrame that refreshes through a backend TailwindCSS JIT compiler (it is not the frontend jit, which is also lovely but works differently). The right bottom is the reason for this app to exist. We use that to translate HTML fragments for development.

**Comment by amlwwalker** [comment]
so what i mean is, when the HTML/JS scripts etc end up in the browser from a page that looks something like

```
<html>
    <head>
        <link rel="stylesheet" href="/style.css">
        <script src="someLibrary.js"></script>
    </head>
    <body>
        <div id="field"></div>
        <script src="myscript.js"></script>
    </body>
</html>
```

when that is loaded and rendered by the browser, `someLibrary.js` will execute before `#field` exists and so if anything in `someLibrary.js` tries to modify the div with id #field it won't be able to because it won't exist yet.

in go-app when you add `Scripts: []string{"..."},` it adds those scripts to the head like `someLibrary` is added in my example.

the script `myscript.js` however is loaded in at the bottom of the file and so at this point div with id `field` will exist and if myscript tries to do anything with it it will execute fine.

What I'm getting at is adding scripts in the head with go-app is straight forward, but adding them at the bottom of the html doc so they load last is not as easy - as you demonstrated with how you have got it to work in your example.

**Comment by amlwwalker** [comment]
thank you however for testing it - i will attempt to get it working as you described as you have demonstrated it works. Do you have the go code snippet  where you manually are calling the `.Call("hightlightAll")` - could you share it by any chance?

**Comment by oderwat** [comment]
@amlwwalker, I think you do not understand how it works. Adding a script in the head with deferring is the same as adding it at the end without. You do not see what you expect because there is no page content when the script runs. Click right on your Site and select "show source", and compare that to the "Elements" view in the DevTools show. The first one is what "prism.js" gets to see and work on.

**Comment by oderwat** [comment]
I just call `hightlightAll()` for this quick test. I normally would target the element itself.

```
app.Window().Get("Prism").Call("highlightAll")
```

**Comment by amlwwalker** [comment]
hey @oderwat thanks for this. For some reason I still can't get the same result you are getting. I have added you to my repository - you should have an invite to it in your email I presume. I've added an issue in that repository outlining what I have done, I wondered if you can have a look?
