### ISSUE TITLE
SetState doesnt work?

### ISSUE THREAD

**Issue by canercetin-randomguy** [maxence-charriere/go-app#782]
Hello. First of all, thank you for this awesome library. I have problems with setting and observing state right now.

**sit tight, this might be stupid.**

https://github.com/canercetin-randomguy/amnesia/blob/master/main.go#L86 Okay so, I simply have a websocket function that returns a message and if it isnt empty, then I wanted to set the contexts state to true. Are that lines work? Yes indeed.

https://i.imgur.com/d7VykF5.png I can print line 85  and 89.

but state is never set to true.

https://github.com/canercetin-randomguy/amnesia/blob/035993077cdb8244a27e5d3675de269df0d7ef90/main.go#L95  Here is a function that runs with page load that observes /newMessage state. It never works, Line 99 and Line 101 never print a thing, cause 

`			ctx.SetState("/newMessage", true)`

never works in https://github.com/canercetin-randomguy/amnesia/blob/035993077cdb8244a27e5d3675de269df0d7ef90/main.go#L88

...help?

**Comment by oderwat** [comment]
Your problem may be that you do not follow the example with `ObserveState().OnChange()`. Try using the appended `.Value(&h.name)` instead of using `GetState()` in the observer.

Two things I do differently:

1. I use a 60-minute timeout Context in a loop like  `conn.Read(wsCTX)` instead of 2 second "polling".
2. I use a function with `ctx.Dispatch()` to do work with the message instead of using the state construct for that.

**Comment by canercetin-randomguy** [comment]
> Your problem may be that you do not follow the example with `ObserveState().OnChange()`. Try using the appended `.Value(&h.name)` instead of using `GetState()` in the observer.
> 
> Two things I do differently:
> 
> 1. I use a 60-minute timeout Context in a loop like  `conn.Read(wsCTX)` instead of 2 second "polling".
> 2. I use a function with `ctx.Dispatch()` to do work with the message instead of using the state construct for that.

handled it with both methods you said, thank you a lot mate. https://github.com/canercetin-randomguy/amnesia/blob/master/main.go
