### ISSUE TITLE
Help: lifecycle basics 

### ISSUE THREAD

**Issue by lolorenzo777** [maxence-charriere/go-app#799]
hello, 
I'm trying to understand the lifecycle of go-app (I've already developped an App in go with wasm but with a grass root framework).

I'm really enthusiast with go-app but not so easy to start :-) 

So I would like to test a simple update of the text of a button when I click on it.

Here is the code of my button component:

```go
type myButton struct {
	app.Compo
	Name string
}

func (c *myButton) Render() app.UI {
	return app.Button().OnClick(c.onClick).Text(c.Name)
}

func (c *myButton) OnMount(ctx app.Context) {
	fmt.Println("component mounted")
	c.Name = "click here"
	c.Update()
}

func (c *myButton) onClick(ctx app.Context, e app.Event) {
	fmt.Println("onClick is called")
	c.Name = "clicked"
	c.Update()
}
```

and the app's code:

```go
type hello struct {
	app.Compo
}

func (h *hello) Render() app.UI {
	return app.Div().Body(
		app.H1().Text("Hello World!"),
		app.Div().Style("margin", "1rem").
			Body(&myButton{}),
	)
}
```

My issues: 
1. the button's text is never initialized
2. the onClick event is well fired but the button's text is not updated

Thank's in advance for your help

**Comment by oderwat** [comment]
Write `Name` lowercase in the component and I think it works.

You basically say: "Use the value I give to the component from the outside" (which is an empty string in your case), but then you change it internally. But go-app will then Go back and initialize it with your external value on the next render.

If you want to use a default, then use one value like `InitialName` and the other as `name`. 

BTW: You will not need to call `c.Update()` as this is standard behavior for the event-handlers anyway. Tell me please if that helped!

**Comment by lolorenzo777** [comment]
> Write `Name` lowercase in the component and I think it works.
> 
> You basically say: "Use the value I give to the component from the outside" (which is an empty string in your case), but then you change it internally. But go-app will then go back and initialize it with your external value on the next render.
> 
> If you want to use a default, then use one value like `InitialName` and the other as `name`.
> 
> BTW: You will not need to call `c.Update()` as this is standard behavior for the event-handlers anyway. Tell me please if that helped!

Thank you.
Can close the issue.

**Comment by suntong** [comment]
> You basically say: "Use the value I give to the component from the outside" (which is an empty string in your case), but then you change it internally. But go-app will then go back and initialize it with your external value on the next render.

Hmm... I'm still not too clear why changing `Name` to lowercase in the component can make the OP works, and why it behave so internally as quoted above.

I ask because I changed my go-app control structure from lowercase to uppercase and it stop working, just as reported in OP. Besides the aforementioned confusing, my understanding from 

https://go-app.dev/components#exported-vs-unexported

is that, 

go-app determine whether a component needs to be updated based on the comparison of the values of _**exported**_ fields.

> Child components are updated only when there is diff with their exported fields, and only exported field are updated.

IE, the doc _recommends_ to use exported components fields, instead of the solution proposed here, unexported fields.

Overall, I'm still very confused about the whole issue, why changing my go-app control structure from lowercase to uppercase and it stop working.

**Comment by oderwat** [comment]
> I'm still not too clear why changing `Name` to lowercase in the component can make the OP work

Because it will not be overwritten after it got changed internally.

Let me try to explain it as I understand it, but in a different way:

<img width="411" alt="image" src="https://github.com/maxence-charriere/go-app/assets/719156/5f85743e-3c3a-4864-a424-b09e93c868fc">

The marked code will create a **new** button component on every render. Then the **existing** one will be updated by the values from this fresh "template" component. But only those that are **exported**.

Imagine that you want to control the button label in the `app` part:

```go
type hello struct {
	app.Compo
}

func (h *hello) Render() app.UI {
	return app.Div().Body(
		app.H1().Text("Hello World!"),
		app.Div().Style("margin", "1rem").
			Body(&myButton{Name: "Counting"}),
	)
}
```

Now think of having other fields in that button, you do not want to reset those internal values from the outside. So the update algorithm makes sure, that only the values that are exported are updated. And if you do not say `Name: "something"` on the outside, you actually say `Name: ""` and therefore the name stays "" and your internal change to something else gets overwritten by it through the update.

If this worked otherwise, you could not have a component that has its own state, or could not update it from the upside (without preparing some setters for it or other complex handling).

As a simple example, think of a counting button, which label you can set from the parent:

```go
type myButton struct {
	app.Compo
	Name  string
	count int
}

func (c *myButton) Render() app.UI {
	return app.Button().
		OnClick(c.onClick).
		Text(fmt.Sprintf("%s: %d", c.Name, c.count))
}

func (c *myButton) OnMount(ctx app.Context) {
	app.Log("component mounted")
}

func (c *myButton) onClick(ctx app.Context, e app.Event) {
	app.Log("onClick is called")
	c.count++
}
```

This way it will use the label you give it, but also counts. I hope this example makes it more clear why (I think) it is designed that way.

By this implementation, you can also change the label of the button without changing (or knowing) about the internal counter. A (stupid) example would be, then you change the `Name: "Counting"` to something like this:

```go
type hello struct {
	app.Compo
}

func (h *hello) Render() app.UI {
	return app.Div().Body(
		app.H1().Text("Hello World!"),
		app.Div().Style("margin", "1rem").
			Body(&myButton{Name: fmt.Sprintf("Counting (at %d)", time.Now().UnixMilli())}),
	)
}
```

Here, it will create a new label every time it renders the "hello" component. Using this code and watching the debug code, you can see how the render is being called on the parent of the component so that it actually can be updated from it.

Another use would be that you give the "Start" for counting from external (let's suppose we do not want to calculate the resulting count but really set it as the internal count):

```go
type myButton struct {
	app.Compo
	Name  string
	Start int
	count int
}

func (c *myButton) Render() app.UI {
	return app.Button().
		OnClick(c.onClick).
		Text(fmt.Sprintf("%s: %d", c.Name, c.count))
}

func (c *myButton) OnInit() {
	app.Log("component mounted")
	c.count = c.Start
}

func (c *myButton) OnMount(ctx app.Context) {
	app.Log("component mounted")
}

func (c *myButton) onClick(ctx app.Context, e app.Event) {
	app.Log("onClick is called")
	c.count++
}
```

And the app would call it like:

```go
type hello struct {
	app.Compo
}

func (h *hello) Render() app.UI {
	return app.Div().Body(
		app.H1().Text("Hello World!"),
		app.Div().Style("margin", "1rem").
			Body(&myButton{Name: fmt.Sprintf("Counting (at %d)", time.Now().UnixMilli()),
			Start: 42,
		}),
	)
}
```

This would copy the external value to the internal one before any `Render()` call happens (`OnMount()` is called after the first `Render()`). Notice: The `Start` could still be updated on later `Render()` calls, but would not interfere with an already started counter, as it is copied on the creation of the component only.

@maxence-charriere I would appreciate it if you could look at my answer, so I do not tell the people the wrong things. Maybe you can also explain it differently. I think that the docs could use an example. Perhaps similar to that I show here.

**Comment by suntong** [comment]
Thank you for such a comprehensive explanation.

> I think that the docs could use an example. Perhaps similar to that I show here.

Yeah I totally concur that the docs could use an example, as I'm anticipating that most starter would have such confusing at the beginning. 

Thanks again
