### ISSUE TITLE
chi-style routing

### ISSUE THREAD

**Issue by Shiro836** [maxence-charriere/go-app#811]
How can I define chi-style(or similar) route like /books/{book_id}. I want to be able to get book_id value in Render and PreRender functions.

**Comment by oderwat** [comment]
You can access it as `ctx.Page().URL()` in `OnPreRender()` (and I think anywhere else where you have `ctx`, like `OnMount()`).

Typically, you want to handle that in `OnMount()` or in `OnNav()`. It depends on where/when your component gets mounted. We use `OnNav()` for all changing paths in the front-end (using a `.*` regex for the route), so we act on that in `OnNav()` in our framework that sits on top of go-app.

You can access the URL as `app.Window().Get("location").Get("href")` in `Render()` too, but only when running in the front-end, and I would not advise that as I believe in strict separation of "model" and "view" in a go-app. But you could add `ctx.Page()` to be part of the model data, I suppose.

Either way, you need to parse your URL by yourself, and you have to add the paths using `app.RouteWithRegexp()` when you want to use components like that. If you intend to use those fields in the back-end, you can simply use chi there in addition to the routing by go-app. This is what we do.

Many, SPA also do not use the URL but the "#" (`location.hash`) for changes in state because "navigating" is more a thing you do when you do not use an SPA/PWA system for your application. But with go-app, this is basically the same, just that you use the hash in `OnNav()`.
