### ISSUE TITLE
js files not reachable for browser when using a different url than / 

### ISSUE THREAD

**Issue by edimoldovan** [maxence-charriere/go-app#815]
I tried changing the "/" to "/brands" in both the client router and server router, as I would need the entire app to run on a different sub-path, but this means none of the static files normally being served from /web work anymore, see below

```
The resource from “http://localhost:8000/web/app.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
The resource from “http://localhost:8000/web/app.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
The resource from “http://localhost:8000/web/wasm_exec.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
```

My main code

```
func main() {
	app.Route("/brands", &hello{})
	app.RunWhenOnBrowser()

	http.Handle("/brands", &app.Handler{
		Name:        "Hello",
		Description: "An Hello World! example",
	})

	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatal(err)
	}
```

Can I do something about this?

**Comment by oderwat** [comment]
We use a chi router in front of the go-app router to route everything that should not be served through go-app can be served through that handler. This is mandatory to create a backend URL on the same domain.

One of our projects has both: A PWA + a normal HTML site using Go-App and GopherJS (for the code in the HTML pages). There, we even use the host SNI information to serve everything through one executable (PWA/API/HTML-Site). While this was a challenging learning experience, we will change that to a container stack behind Traefik soon. Which I would suggest, too, if your HTML pages get a bit more complicated.

That is basically what @norazlan shows you. He omitted to add a handler for `http.Handle("/", pageHandler)` that would serve your root page as normal HTML.

We use the chi router because it is easier to express the routes with wildcards and implement an API and, for example, adding middleware that compresses the WASM data on the fly.

P.S.: I still struggle with putting go-app's resources into a subdirectory (other than "/web") but I guess it is not that hard, I just had no time to figure that out.

**Comment by oderwat** [comment]
I told you what you can do to serve it from the same app (using a normal router and let the route decide if you send it to go-app or another HTTP-handler). But I also point out that doing that mixes a (RESTful) backend, "normal" HTTP/HTML and a PWA in the same codebase and that you either need to implement TLS and all of those things yourself or have a reverse proxy in the mix anyway. My experience is that it is easier to just write the PWA and the HTML page in their own code and run it under localhost:1234 and put that together with Traefik into a docker-compose. This lets you update each component without restarting the other. Of course, is this "too much" if you only have a login page and the PWA. But then I wonder why you have a login page at all and do not serve that as the first page of the PWA.

**Comment by oderwat** [comment]
BTW: Go-App can do both: CSR and SSR ... but it is meant to write a PWA. I doubt that it makes a lot of sense to SSR parts of the PWA, but you can do that. AFAIK, using raw HTML with (large) HTML from the backend, is not working well. I have some "go-"apps that use iframes and SSR to have dynamic CSS and HTML, but that is a playground for developing TailwindCSS and go-app declarative code for HTML snippets. Not an application for a client.

**Comment by oderwat** [comment]
> If so, I feel I am loosing the benefits of go-app as Go is "traditionally" running on the backend 

The benefit of go-app is running Go in the front-end. We do not render anything in the backend. We have an app that has a product website with it and this site I wanted to be written with Go for the frontend but not being a PWA because it is the landing page for the application and there you do not want an interested person to wait for the go-app download. So, we made that a "normal" website and used GopherJS for all the "scripting" on that page (which is not very much anyway).

**Comment by oderwat** [comment]
>  there isn't really a lot of benefit there

It is all about writing Go code for the frontend of a PWA. There are, of course, plenty of JS options and if JS is something you want to use, there is no real reason to go with Go in my opinion.
