### ISSUE TITLE
How to dynamically add new lines to the view

### ISSUE THREAD

**Issue by rtrzebinski** [maxence-charriere/go-app#834]
Question - how can I dynamically add text to component **as a new line**?

Case: I have a paragraph that displays input validation messages.

These are held in `c.Error` variable that I can manipulate dynamically - all good.

However I can not figure out how to add each error as a new line, I tried `\n`, `</br>` but nothing works.

I checked documentation, I see raw html option there, but I'm not sure how to use it correctly or whether this is a correct approach.

I'd appreciate a hint, thank you.

**Comment by oderwat** [comment]
You could use raw HTML, but I would suggest using something like this:

```go
app.P().Body(func(txt string) []app.UI {
	s := strings.Split(txt, "\n")
	var ui []app.UI
	for i, p := range s {
		if i != 0 {
			ui = append(ui, app.Br())
		}
		ui = append(ui, app.Text(p))
	}
	return ui
}(c.error)...)
```

P.S.: You may want to make `c.error` a slice of string or `app.UI` and / or use the `Range().Slice()` construct.
P.P.S: Having `c.Error` instead of `c.error` may create a problem if you want to be able to change it from inside the component.

**Comment by rtrzebinski** [comment]
Thank you @oderwat this worked just fine:

```go
			app.P().Body(
				app.Range(c.validationErrors).Slice(func(i int) app.UI {
					return app.Div().Body(
						app.Text(c.validationErrors[i].Error()),
						app.Br(),
					).Style("color", "red")
				}),
			),
```
