### ISSUE TITLE
Hello world example is broken on the Getting Started page

### ISSUE THREAD

**Issue by leighmcculloch** [maxence-charriere/go-app#840]
I copy-pasted the code from the hello world example:

https://go-app.dev/getting-started

When building the client side and server side code, both succeed with no errors.

However, when running the application, and opening the browser, I see this error:

<img width="521" alt="Screenshot 2023-06-30 at 11 17 13 PM" src="https://github.com/maxence-charriere/go-app/assets/351529/4ae09d4f-8a1f-4864-8725-a348088ec420">

The text reads:

> TypeError: import gojs:runtime.scheduleTimeoutEvent must be an object

**Comment by leighmcculloch** [comment]
Ah, so this error happens when building with Go 1.21rc2.

The error does not occur with Go 1.20.5.

So it appears something that's coming in the next version of Go is going to break go-app.

**Comment by oderwat** [comment]
> So it appears something that's coming in the next version of Go is going to break go-app.

Or something in the RC is broken and needs to be fixed ;-)

**Comment by leighmcculloch** [comment]
The [Go 1.21 release notes](https://tip.golang.org/doc/go1.21) contain the following statement:

> The Go scheduler now interacts much more efficiently with the JavaScript event loop, especially in applications that block frequently on asynchronous events.

So it's possible the JS runtime functions have been refactored,

**Comment by leighmcculloch** [comment]
According to this post below the import module has changed from `go` to `gojs`. https://gophers.slack.com/archives/C4GU6CHSQ/p1688458505006959

**Comment by mlctrez** [comment]
The wasm_exec.js content at [pkg/app/scripts.go#L11](https://github.com/maxence-charriere/go-app/blob/1f671917400880c5dadc7558d28edabcfa2297e3/pkg/app/scripts.go#L11) is from a version prior to go version 1.21

Replacing the wasm_exec.js contents with the version from a 1.21 go installation seems to get past this error.

I'm not sure of what the right approach to solving this long term.

Certainly upgrading the go-app minimum go version would be one option, but I believe @maxence-charriere has been hesitant to do this in the past.

Including multiple versions of wasm_exec.js in the generated script.go seems bad as well since this file might change again in the future.
