### ISSUE TITLE
Prevent constant update of component when resizing window or forcefully rerender an unexported property

### ISSUE THREAD

**Issue by thejezzi** [maxence-charriere/go-app#847]
Hi there,

I have a component that renders a table with pagination and therefore needs to load new data when going one page further. The data is loaded and the render function is executed, but the app does not update the DOM unless I make the field an exported field. Then the DOM is updated but when I resize the window hundreds to thousands of new renders are executed. I have already cached the results but I would still like to avoid the rerenders. 
 - Am I doing something wrong?
 - Is there a way to prevent the rerendering? The resizer is only executed at the end of the resizing, so it doesn't really help me.
 
 This is the component:
 
 ```go
 type MyTable struct {
	a.Compo

	response    myapp.ResponseBody[[]myapp.Analysis]
	CurrentPage int
	TotalPages  int
	ItemsCount  int
}

func (p *MyTable) OnMount(ctx a.Context) {
	ctx.Async(func() {
		p.FetchData()
		ctx.Dispatch(func(ctx a.Context) {
			p.Update()
		})
	})
}

func (p *MyTable) OnUpdate(ctx a.Context) {
	ctx.Async(func() {
		originalResponse, ok := util.UseStore().Get("myapp-analysis").(myapp.ResponseBody[[]myapp.Analysis])

		if ok {
			p.response = originalResponse
			p.SetInitialValues()
			p.CalcPagination()
			p.Update()
		}
	})
}

func (p *MyTable) FetchData() {
	// load data once

	url := "/api/myapp/analysis"
	query := fmt.Sprintf("?limit=%v&offset=%v", p.ItemsCount, (p.CurrentPage-1)*p.ItemsCount)

	resp, err := http.Get(url + query)
	if err != nil {
		a.Log("Error getting analysis: %v", err)
		return
	}
	defer resp.Body.Close()

	// parse response
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		a.Log("Error reading response body: %v", err)
		return
	}

	// unmarshal response
	var response myapp.ResponseBody[[]myapp.Analysis]
	err = json.Unmarshal(body, &response)
	if err != nil {
		a.Log("Error unmarshalling response: %v", err)
		return
	}

	p.response = response

	// Using store in case the user resizes the window. If so the whole component
	// gets re-rendered and the data is lost. So we save it in the store and
	// retrieve it on update
	util.UseStore().Set("myapp-analysis", p.response)

	p.Update()
}

func (p *MyTable) SetQuery(key, value string) {
	currentUrl, err := url.Parse(a.Window().URL().Path)
	if err != nil {
		a.Logf("Error parsing url: %v", err)
		return
	}

	query := currentUrl.Query()
	query.Set(key, value)
	currentUrl.RawQuery = query.Encode()

	a.Window().Get("history").Call("pushState", nil, "", currentUrl.String())
}

func (p *MyTable) SetInitialValues() {
	if p.CurrentPage == 0 {
		page := a.Window().URL().Query().Get("page")
		if page != "" {
			p.CurrentPage, _ = strconv.Atoi(page)
		} else if p.CurrentPage == 0 {
			p.CurrentPage = 1
		}
	}

	if p.ItemsCount == 0 {
		p.ItemsCount = 10
	}
}

func (p *MyTable) CalcPagination() {
	p.TotalPages = p.response.Total / p.ItemsCount
	if p.response.Total%p.ItemsCount > 0 {
		p.TotalPages++
	}
}

func (p *MyTable) renderRow(row myapp.Analysis) a.UI {
	// Some icons for better readability
	icon := ""
	switch strings.ToLower(row.App) {
	case "app1":
		icon = app1Icon
	case "app2":
		icon = app2Icon
	case "app3":
		icon = app3Icon
	}

	date := util.RenderDateDE(row.Created)
	myappId := strconv.FormatInt(row.myappId, 10)

	return ui.DataRow().
		Cell(a.Text(date)).
		Cell(a.Text(myappId)).
		Cell(
			a.Div().Class("flex gap-2").Body(
				a.If(icon != "", a.Raw(icon)),
				a.Text(row.App),
			),
		).
		Cell(
			a.A().
				Class("w-full text-center").
				Href("/myapp/details/" + myappId).Body(
				a.Raw(LinkIcon),
			),
		)
}

func (p *MyTable) Render() a.UI {

	p.SetInitialValues()
	p.CalcPagination()

	return a.Div().Body(
		a.If(p.response.Total > 0,
			ui.DataTable().
				Header("Erstellt am", "myapp ID", "App", "Link").
				Rows(a.Range(p.response.Data).Slice(func(i int) a.UI {
					return p.renderRow(p.response.Data[i])
				})).
				Pagination(
					ui.Pagination().
						TotalPages(p.TotalPages).
						PerPage(p.ItemsCount).
						CurrentPage(p.CurrentPage).
						OnClick(func(page int, ctx a.Context) {
							p.CurrentPage = page
							p.SetQuery("page", strconv.Itoa(page))
							p.FetchData()
						}),
				),
		).Else(
			a.P().Text("Keine Daten vorhanden"),
		),
	)
}
 ```

**Comment by oderwat** [comment]
First: You should not do anything else than render existing data in `OnRender()`. Do this in `OnMount()` and then catch the resize with an event-handler. Think of `OnRender()` as something that has read-only access to the state and creates the current representation. Go-App compares this "template" to what the actually DOM is and updates this accordingly.

Second: You will get many events on the new handler when resizing the window. To handle this, we use a [debouncer](https://github.com/metatexx/go-app-pkgs/blob/master/debounce/debounce.go) and the `ctx.PreventUpdate()` which was getting introduced for some similar problems.

See here: https://github.com/maxence-charriere/go-app/pull/711#issuecomment-1137194754

Usually, one also does not need `OnUpdate()` because this if for getting notified if your parent component changes exported fields of your component. I am not certain, but you may have missed what it really is used for.

I would also not use the value inside the DOM for getting the page, as you do in `SetInitialValues()`. To me, the "page" is a state variable in the component (the model) and changes to it, will update the view (because of a new render result). The variable in the component then gets updated in our code, usually by adding an `OnInput()` handler. For your case, I would probably use `OnChange()` to not trigger while typing.

So overall, my approach and understanding of how to use components is close to the MCV model with the model being the (private) values in your structure and initialized in `OnMount()` and later changed by the controller, the view is `OnRender()` and only uses the state in the model (nothing else ever). The controller is given through the event handlers. This gets extended by the exported variables (the "input") which should get transferred to the internal state in `OnMount()/OnUpdate()`. With this concept we create some fairly large projects.

**Comment by thejezzi** [comment]
Thank you for answering! :)

1. Yeah I know ... but if I do as you suggest than the following happens:

![image](https://github.com/maxence-charriere/go-app/assets/38394992/17930793-c4f3-450e-899d-a67540061b4c)
I removed the `OnUpdate` Handler and put the `SetInitialValues()` Function into `OnMount` like you prescribed like so:

```go
func (p *MyAppAnalysisTable) OnMount(ctx a.Context) {
	a.Log("OnMount called")
	p.SetInitialValues()
	p.CalcPagination()

	ctx.Async(func() {
		p.FetchData()
		ctx.Dispatch(func(ctx a.Context) {
			p.Update()
		})
	})
}

func (p *MyAppAnalysisTable) Render() a.UI {
	return godmin.DataTable().
		Header("Erstellt am", "MyApp ID", "App", "Link").
		Rows(a.Range(p.Response.Data).Slice(func(i int) a.UI {
			return p.renderRow(p.Response.Data[i])
		})).
		Pagination(
			godmin.Pagination().
				TotalPages(p.TotalPages).
				PerPage(p.ItemsCount).
				CurrentPage(p.CurrentPage).
				OnClick(func(page int, ctx a.Context) {
					p.CurrentPage = page
					p.SetQuery("page", strconv.Itoa(page))
					p.FetchData()
				}),
		)
}
```

2. Awesome, will look into that, but I'd rather have my component not rerender in the first place.

3. No I didn't miss it but like a mentioned above my table is not rendering anything except the table header when I remove it.

4. Yeah why not, page could be a field of the component but this doesn't change anything for the sake of rendering this goddamn table 😄 oh and I don't get where I should put the `OnInput` handler, there is no input in my table.

**Comment by oderwat** [comment]
I would start with writing all field names in lower case to avoid that they get changed because they are "external" parameters to the component.

If your table does not render/update, you need to find out why that is. Add debugging (we use the `dbg` package you find in the same repository where the debouncer is) to understand what your code is doing. You could add `dbg()` in the start and end of any function and go routine (async). To see how the code really works.

> Awesome, will look into that, but I'd rather have my component not rerender in the first place.

This is why it uses `ctx.PreventUpdate()`, without an update, it does not call `Render()`. The debouncer will stop the backend being hammered, with the update prevention it skips calling render before there actually can be changes.

**Comment by thejezzi** [comment]
> I would start with writing all field names in lower case to avoid that they get changed because they are "external" parameters to the component. I just spotted: a.Range(p.Response.Data) this Response needs to be lower case!

> If your table does not render/update, you need to find out why that is. Add debugging (we use the dbg package you find in the same repository where the debouncer is) to understand what your code is doing. You could add dbg() in the start and end of any function and go routine (async). To see how the code really works.

This really worked in the end. My component used a lot of nested components and therefore multiple state variables, so exporting the struct fields of my table component fixed everything.

Thank you so much!

> This is why it uses ctx.PreventUpdate(), without an update, it does not call Render(). The debouncer will stop the backend being hammered, with the update prevention it skips calling render before there actually can be changes.

I didn't need it in the end but still and awesome solution 👍🏼 !
