### ISSUE TITLE
Share data hierarchy in Go like event bubble in js

### ISSUE THREAD

**Issue by gepengscu** [maxence-charriere/go-app#884]
The following is a Form component.
The question is that how the form component can get or set the form items data? 
The form items may be children or children's children of form. 
I solved that by dispatching a javascript CustomEvent in form item OnMount to let the form (listen on the custom event) knowns that a form item mounted, and wrap the form item data and some callbacks in the js event. 
But I don't think it's a good method. 
Is there any way to share data hierarchy in Go like event bubble in js?
```go
Form struct {
  app.Compo
  Body []app.UI
}

FormItem struct {
  app.Compo
  Body []app.UI
  Label string
}

Demo struct{
  app.Compo
}

func (this *Demo) Render() app.UI{
  return &Form{
    Body: []app.UI{
       &Item{Label : "UserName", Body: []app.U{app.Input()}},
       app.Div().Body(&Item{Label : "UserName", Body: {app.Input()}}),
    }
  }
}
```

**Comment by oderwat** [comment]
I am not sure what you are asking for. You should be able to traverse the elements by using the `app.UI` methods like `GetChildren()` and work on their `JSValues()`. You could also create an interface that is shared by all your possible form items that have some way to handle the set/get and whatever you want to be possible, and use this instead of the `app.UI`.

**Comment by gepengscu** [comment]
Thank you!
