### ISSUE TITLE
Signal based change detection

### ISSUE THREAD

**Issue by JulienLecoq** [maxence-charriere/go-app#941]
Are there any plans to support signal-based change detection, given the current trend? Modern front-end frameworks are increasingly adopting signal-based change detection. This mechanism automatically updates the UI when certain variables change, eliminating the need to manually update the UI by calling an 'update()' function.

**Comment by oderwat** [comment]
I kind of wonder about your inquiry as there are no manual updates in Go-App (for the most part) for the developer. 

The term "signals" seems a bit ambiguous as my first idea when it comes to "signals" is about state changes and component interactions like https://go-app.dev/states, which is part of Go-App already.

I saw "signals" mentioned for AngularJS where the signaling idea tries to avoid patching the browser engine for all the places where updates could appear (and check for all possible effects). But Go-App is not a JS Framework and works not like that at all.

In Go-App there is no browser patching at all and all changes to the DOM are controlled by the UI routine and happen on the Go language level. I do think that there could be optimizations there, but in a totally different way. As I understand it, Go-App is basically a loop-driven (Immediate Mode) model, that has optimizations to not re-render everything and even if it renders it, it is often not updating the DOM or does it quite efficient.

I may be ignorant about the JS world (and for a reason). May I ask what your idea is on what level can Go-App utilize the "thing" you are talking about?

**Comment by maxence-charriere** [comment]
@oderwat said it all.

**Comment by JulienLecoq** [comment]
@oderwat Yes, I was talking about it for performance reasons to avoid launching an update mechanism that checks modifications when there are none. This is now used in Angular, SolidJS, Svelte, Vue.js, Qwik and surely some others.
I don't know how go-app compares to those frameworks in term of performance and if signals could improve performance, but it might be good to keep this idea in mind for later?

**Comment by oderwat** [comment]
@JulienLecoq What is your concrete problem with Go-App? Maybe there is a solution if you tell us about it!

**Comment by JulienLecoq** [comment]
Well I already kind of explained it already, using signals can have several benefits:

- maybe better perf?
- no need to use ctx.Update() anymore, I just had a case where I needed to do this. I was dealing with updating my app depending on the theme preference of the user. Btw, the doc seems outdated here: https://go-app.dev/components#updates. It says that we can do: c.Update() whereas it's only available on the context not the component itself.
- better encapsulation since we don't rely on the distinction between exported and unexported fields to update the UI.

**Comment by oderwat** [comment]
* Using `ctx.Update()` is "signaling" that there is an update check needed. If you want to make this a "real" signal, just create one on the component and send that signal instead. I do not see the immediate value and we do generally not use any signalling in our apps, because I believe that having a callback function is superior because it is type safe and avoids conversions and JS interactions.
* If you require `ctx.Update()` when not having a context you can store the context inside the component (or anywhere else) which is (afaik) similar on the old way to call Update() on it. You need to make sure that the context is still valid (the component is still mounted).
* Is your idea, that you make a list of changed values that are updated and use those instead of checking against the full set? I don't think that this would speed up things, it may even make it worse, especially if you need to allocated and free memory for creating such lists. I am pretty sure, that comparing the results of the new "Render()" against the DOM is a lot quicker than creating lists of changes and then trying to figure out what you need to change in the DOM from those lists. You could stay with using `Render()` though. But what is the gain? You still need to have exported fields (internal fields are meaningless for this whole topic in my eyes). How else could you update the component from the outside without adding a lot of extra information (which end up having a struct with options most likely) You also need to consider on how you want to store what is that thing that was changed? A field name in an object? A reference to a memory address of a value in some structure? What about hierarchies of changes? What about multiple changes in the same tick, they even may cancel each other out. I do not think that Go-App faces the same problems as JS frameworks in that regard.
* What bothers me with Go-App is, that we sometimes need to render all the data to have a minimal change in the result. But working with large lists and complex applications, we actually did not run into big difficulties. But we also use techniques like data windows and scroll handlers to keep the size of lists small. This is about lists with 1000s of entries though. I personally think that using the "Render()" based approach is very smart and makes Go-App useable in the first place.
