### ISSUE TITLE
Help: How do I navigate back?

### ISSUE THREAD

**Issue by Skarlso** [maxence-charriere/go-app#956]
Hello 👋 

I would like to ask for some assistance. :) How do I navigate back?

I reliase I have to somehow unload the current component and load the previous component. 🤔  I'm just wondering how do I do that? Do I add a `prev` reference to the component and call Render? But before that, clear any states of the current component. And maybe do that on a button click like, a `<-` backpointing arrow. Or is there a better way to do that?

I was trying to read up the docs on it, but failed.

**Comment by oderwat** [comment]
It actually depends on what you call "back" and how you define the "location" for your app. You can use multiple routes which will switch your components automatically which (I think) is the original idea for the navigation. Go-App also supports "#" Anchors. This will make "back" the same back as in a normal website. 

Another way (and what we prefer) is a more GUI approach which uses a common root component and switch your "view" based on some input. You can also just have an internal "state" for your application. You can even combine the "root" component with URL navigation by using the `OnNav()` to update the components individually by the URL. Something like having the same "Template" but the navigation and the page components are rendered based on the current URL.

In the end it is up to you and what your App should look like. For the components internal states and the cleanup, you need to implement "OnInit()", "OnMount()" and if needed "OnDismount()" to free resources. The components then have the `Render()` function(s) change what they show, which will update the DOM in the browser as one component does not show another component anymore. For example.

P.S.: I kind of struggle to explain it, because there is really a lot of freedom when you do not "just" use the Go-App "Routes" for switching components and leave the realm of "it looks and works like a website".

**Comment by Skarlso** [comment]
Ah gotcha... Hm, This requires some refactoring on my part then. I don't think I made it easy for myself to switch between my views. :D But I get what you are saying. I'm using URLs. I'm using a view that I'm "switching" to once a button is pressed and content is set. So I don't have a root element which I can tell based on internal things on what to display.

Like tabs or somesuch. But I'll figure something out then. :) Thank you for your input! :)
