### ISSUE TITLE
Example code doesn't compile

### ISSUE THREAD

**Issue by elfprince13** [maxence-charriere/go-app#958]
Hi - none of the example code in the README or the Getting Started docs actually compiles:

```console
cannot use &hello{} (value of type *hello) as func() app.Composer value in argument to app.Route
```

Not really sure what to make of this.

**Comment by oderwat** [comment]
It seems that @maxence-charriere is slow with updating the docs (probably because they are going to be moved somewhere else).

You need to replace `&hello{}` with `app.NewZeroComponentFactory(&hello{}))` or `func() app.Composer { return &hello{} }`

Alternatively you could use V9 until the docs are updated for the latest release.

@maxence-charriere I do not know how and where you want to move the docs. I just checked out https://www.gitbook.com/ and really like that (which would keep the doc in the same repository, which I would also prefer, as I stated some time ago). Using something like that would make it pretty easy for you to watch the changes and the community could expand the docs freely. I think that this would be "cooler" than using go-dev for the docs, because it would free up resources and still leave you all the control. METATEXX may sponsor this if it is a problem with pricing.

**Comment by maxence-charriere** [comment]
routing related doc has been updated.

Thanks for the suggestion @oderwat. I ll take a look.
