### ISSUE TITLE
Login in a go-app

### ISSUE THREAD

**Issue by Zirbo** [maxence-charriere/go-app#978]
Hi,
first of all: thank you for your amazing work on this project!
Are there any plans to introduce a standard way to handle logins in go-app in the short term?
If not... I saw you have a login mechanism in https://murlok.io/, did you use any framework you would suggest? (although i only plan to implement a userid/password mechanism for my app)

**Comment by maxence-charriere** [comment]
Hi, thanks for the kind words.

There are no plans to introduce a standard way to handle logins in go-app at this time. There are many ways to handle login, and it would be a significant time sink for me to maintain.

For Murlok.io, I implemented an OAuth mechanism with Battle.net because I wanted to minimize the amount of authentication work I needed to do.

**Comment by Zirbo** [comment]
Understood :)
Thank you :)
