### ISSUE TITLE
How to load on application faster?

### ISSUE THREAD

**Issue by BlackMocca** [maxence-charriere/go-app#995]
i build application and i got wasm 18mb that file so big that not work for external user
i want to know how to client load first page was faster, i thought got 2 way   

1. compressed static file between network (wasm, app.js, app.css)
        - for now, when app serve will be generate serve core file default (app.js exec.js, app.js, etc) it's hard to config serve static file through web server or middleware
        - i trying to use [Echo](https://github.com/labstack/echo) for serve static asset with compressed middleware but does not work result is 404 NOT FOUND
2. reducing wasm file 
        - i read a document a lot for that but from my opinion "build wasm file with golang command is suite for develop" then using [binaryen](https://github.com/WebAssembly/binaryen) optimize wasm
        - could you recommend how to reduce size in another way if possible?
    
**Expect Feature**

1. Can Generate core File app.css, app.js, manifest.webmanifest, wasm_exec.js 
2.(Optional) path parameter like /user/:id 

**Reference**
Code: https://github.com/BlackMocca/go-lightweight-scheduler-ui
Official recommend: https://go.dev/wiki/WebAssembly

Sorry for my english

**Comment by BlackMocca** [comment]
i can already found out of compressed wasm
```golang
	http.HandleFunc("/web/app.wasm", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Encoding", "gzip")
		w.Header().Set("Content-Type", "application/wasm")
		bu, err := ioutil.ReadFile("./web/app.wasm.gz")
		if err != nil {
			panic(err)
		}
		w.Write(bu)
	})
```

**Comment by oderwat** [comment]
I was not at a computer and so I am a bit late. I hope I can still give you some more hints:

You may want to check out what we do in this repository: https://github.com/oderwat/go-nats-app

*  Like splitting WASM Frontend + Go Backend (check the mage.go file)
* Using compression (https://github.com/oderwat/go-nats-app/blob/e5eafd92c43db87840e284877e58578479b4bbd1/back/back.go#L130).
*  This can be extended by adding 
```
		LoadingLabel:            "Loading... {progress}%",
		WasmContentLengthHeader: "X-Uncompressed-Content-Length",
```
 to the `app.Handler`.

Another hint is to avoid using "net/http" for the` http.Client` all together. This takes up multiple MB in the frontend. Instead make use of the JS script interface directly (basically: `Await(app.Window().Call("fetch", url, requestOptions), "fetchURL")`) with an `Await` implementation in Go or by using some JS snipped (added through `app.Handler.RawHeaders` for example). This can then calls some Go routines for the fetch result (you export to JS using "app.FuncOf()").

**Comment by oderwat** [comment]
Because I can not share our `Await()` implementation I just asked ChatGPT to create a fetch implementation using go-app and javascript fetch. This is untested but looks good on first sight. But you have to replace `js.` (`syscall/js`) with `app.` (which wraps the JS interface when using Go-App).

``go
package main

import (
	"encoding/json"
	"fmt"
	"syscall/js"

	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

type MyApp struct {
	app.Compo
	Data string
}

func (m *MyApp) Render() app.UI {
	return app.Div().Body(
		app.H1().Text("HTTP Fetch Example in Go using WASM"),
		app.Button().Text("Fetch Data").OnClick(m.onFetchData),
		app.If(m.Data != "", app.Div().Text(m.Data)),
	)
}

func (m *MyApp) onFetchData(ctx app.Context, e app.Event) {
	go m.fetchData()
}

func (m *MyApp) fetchData() {
	url := "https://api.example.com/data"

	// Use JavaScript fetch to make the request
	js.Global().Call("fetch", url).Call("then", js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		response := args[0]
		return response.Call("json").Call("then", js.FuncOf(func(this js.Value, args []js.Value) interface{} {
			var result map[string]interface{}
			if err := json.Unmarshal([]byte(args[0].String()), &result); err != nil {
				fmt.Println("Error decoding response:", err)
				return nil
			}

			// Update the component state
			m.Data = fmt.Sprintf("Fetched Data: %v", result)
			app.Dispatch(func() {
				m.Update()
			})
			return nil
		}))
	})).Call("catch", js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		fmt.Println("Error making request:", args[0])
		return nil
	}))
}

func main() {
	app.Route("/", &MyApp{})
	app.RunWhenOnBrowser()

	select {} // Prevent main from exiting
}

// Export a Go function to JavaScript to interact with the DOM (for WASM purposes)
func init() {
	js.Global().Set("fetchData", js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		go func() {
			fmt.Println("fetchData function called from JavaScript")
		}()
		return nil
	}))
}
```

**Comment by BlackMocca** [comment]
thank you for your answer. i will see your code and trying  from your hint
for now after i compress i got 2.7mb from 18mb

**Comment by dxps** [comment]
Indeed, as Hans (@oderwat) mentioned, changing the implementation of the HTTP client from `net/http` to something that uses browser's native `fetch` function lowers the WASM size considerably.

I did an experiment and used [wasm-fetch](https://github.com/marwan-at-work/wasm-fetch) (currently copied its source into the project just because it misses `//go:build js && wasm` annotations, I'll send a PR to that project).

The WASM file size decreased from ~22MB to ~13MB. 
Furthermore, delivered it as compressed (and serve it from memory, just to be as fast as possible).

And here are the figures:

| before |  after |
| --- | --- |
| ![Image](https://github.com/user-attachments/assets/be02d425-5db8-47d4-80a1-0591e8da6b3d) | ![Image](https://github.com/user-attachments/assets/84e75730-f83d-45c6-93bd-abd02bdced8b) |

You can find the source of in [go-app_files_mgmt](https://github.com/dxps/go_playground/tree/master/go-app_samples/go-app_files-mgmt) sample.

Hope it helps!
